CREATE TABLE NOTIFICATION(
	id BIGINT AUTO_INCREMENT PRIMARY KEY,
	notifier BIGINT NOT NULL,
	receiver BIGINT NOT NULL,
	outerid BIGINT NOT NULL,
	TYPE INT NOT NULL,
	gmt_create BIGINT NOT NULL,
	STATUS INT DEFAULT 0 NOT NULL
)
